// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/shopspring/decimal"
)

type Order struct {
	ID        string
	UserID    string
	Symbol    string
	Side      string
	Type      string
	Price     decimal.Decimal
	Quantity  decimal.Decimal
	FilledQty decimal.Decimal
	Status    string
	CreatedAt int64
	UpdatedAt int64
}

type Trade struct {
	ID          string
	Symbol      string
	BuyOrderID  string
	SellOrderID string
	Price       decimal.Decimal
	Quantity    decimal.Decimal
	ExecutedAt  int64
}
