// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/shopspring/decimal"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'CANCELED', updated_at = $2
WHERE id = $1
RETURNING id, user_id, symbol, side, type, price, quantity, filled_qty, status, created_at, updated_at
`

type CancelOrderParams struct {
	ID        string
	UpdatedAt int64
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.UpdatedAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.FilledQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, user_id, symbol, side, type,
    price, quantity, filled_qty, status,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
) RETURNING id, user_id, symbol, side, type, price, quantity, filled_qty, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID        string
	UserID    string
	Symbol    string
	Side      string
	Type      string
	Price     decimal.Decimal
	Quantity  decimal.Decimal
	FilledQty decimal.Decimal
	Status    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Symbol,
		arg.Side,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.FilledQty,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.FilledQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenOrdersBySymbol = `-- name: GetOpenOrdersBySymbol :many
SELECT id, user_id, symbol, side, type, price, quantity, filled_qty, status, created_at, updated_at FROM orders
WHERE symbol = $1 AND status IN ('NEW', 'PARTIAL')
ORDER BY created_at ASC
`

func (q *Queries) GetOpenOrdersBySymbol(ctx context.Context, symbol string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOpenOrdersBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.FilledQty,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, symbol, side, type, price, quantity, filled_qty, status, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.FilledQty,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
