// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package repository

import (
	"context"

	"github.com/shopspring/decimal"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    id, symbol, buy_order_id, sell_order_id,
    price, quantity, executed_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
) RETURNING id, symbol, buy_order_id, sell_order_id, price, quantity, executed_at
`

type CreateTradeParams struct {
	ID          string
	Symbol      string
	BuyOrderID  string
	SellOrderID string
	Price       decimal.Decimal
	Quantity    decimal.Decimal
	ExecutedAt  int64
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.ID,
		arg.Symbol,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.Price,
		arg.Quantity,
		arg.ExecutedAt,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.BuyOrderID,
		&i.SellOrderID,
		&i.Price,
		&i.Quantity,
		&i.ExecutedAt,
	)
	return i, err
}

const getTradesByOrder = `-- name: GetTradesByOrder :many
SELECT id, symbol, buy_order_id, sell_order_id, price, quantity, executed_at FROM trades
WHERE buy_order_id = $1 OR sell_order_id = $1
ORDER BY executed_at DESC
`

func (q *Queries) GetTradesByOrder(ctx context.Context, buyOrderID string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByOrder, buyOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.Price,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesBySymbol = `-- name: GetTradesBySymbol :many
SELECT id, symbol, buy_order_id, sell_order_id, price, quantity, executed_at FROM trades
WHERE symbol = $1
ORDER BY executed_at DESC
`

func (q *Queries) GetTradesBySymbol(ctx context.Context, symbol string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.Price,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
